export const siteConfig = {
  doctor: {
    name: "Dr. Sugandha Priyadarshini",
    prefix: "Dr.",
    qualifications: ["MBBS", "MD (Radiology)"],
    title: "Consultant Radiologist",
    tagline: "Precision Imaging & Women's Imaging Specialist",
    shortBio:
      "Consultant Radiologist specializing in diagnostic imaging, women's imaging, and 3 Tesla MRI reporting — serving the people of Deoghar and Jharkhand with accuracy and compassion.",
    longBio: [
      "Dr. Sugandha Priyadarshini is a Consultant Radiologist with an MD in Radiology, dedicated to providing accurate and timely diagnostic imaging services. Her expertise spans the full spectrum of radiology, with a special focus on women's imaging and high-field 3 Tesla MRI reporting.",
      "She is skilled in interpreting MRI, CT, ultrasound, and X-ray studies, with particular interest in neuroimaging, abdominal imaging, and women's health imaging including breast imaging and obstetric ultrasound. Her reporting is known for its precision and clinical correlation.",
      "At Care Diagnostics, Dr. Priyadarshini provides comprehensive diagnostic imaging services supporting neurosurgical and multi-speciality care at Hope NeuroTrauma Hospital. Her 3T MRI reporting ensures the highest image quality for accurate diagnosis.",
    ],
    photo: "/doctor-photo.png",
    yearsOfExperience: 8,
  },
  hospital: {
    name: "Care Diagnostics & Hope NeuroTrauma Hospital",
    shortName: "Care Diagnostics",
    tagline: "Advanced Imaging. Accurate Diagnosis. Better Care.",
    address: {
      line1: "Castairs Town",
      line2: "Near Bajla Mahila College",
      line3: "Deoghar, Jharkhand — 814112",
      country: "India",
      full: "Castairs Town, Near Bajla Mahila College, Deoghar - 814112, Jharkhand, India",
    },
    mapEmbedUrl: "https://www.google.com/maps?q=Bajla+Mahila+College,+Deoghar,+Jharkhand+814112&output=embed",
    mapLinkUrl: "https://www.google.com/maps/search/?api=1&query=Bajla+Mahila+College+Deoghar+814112",
  },
  contact: {
    phone: "+91 90000 00000",
    phoneHref: "+919000000000",
    emergency: "+91 90000 00000",
    emergencyHref: "+919000000000",
    email: "care@carediagnostics.in",
    whatsapp: "+919000000000",
    whatsappMessage: "Hello, I would like to book a radiology consultation.",
  },
  timings: [
    { day: "Monday", hours: "9:00 AM – 5:00 PM" },
    { day: "Tuesday", hours: "9:00 AM – 5:00 PM" },
    { day: "Wednesday", hours: "9:00 AM – 5:00 PM" },
    { day: "Thursday", hours: "9:00 AM – 5:00 PM" },
    { day: "Friday", hours: "9:00 AM – 5:00 PM" },
    { day: "Saturday", hours: "9:00 AM – 2:00 PM" },
    { day: "Sunday", hours: "Closed (Emergency Only)" },
  ],
  specializations: [
    { icon: "Brain", title: "3 Tesla MRI Reporting", description: "High-field 3T MRI interpretation for neuroimaging, musculoskeletal, and abdominal studies with superior image quality and detail." },
    { icon: "HeartPulse", title: "Women's Imaging", description: "Comprehensive women's imaging including breast ultrasound, mammography correlation, and obstetric imaging with compassionate care." },
    { icon: "Activity", title: "CT Scan Reporting", description: "Multi-slice CT interpretation for head, chest, abdomen, and vascular imaging with contrast-enhanced studies." },
    { icon: "Stethoscope", title: "Ultrasound (USG)", description: "Diagnostic ultrasound for abdomen, pelvis, thyroid, Doppler, and obstetric scanning with real-time guidance." },
    { icon: "Baby", title: "Obstetric Imaging", description: "Fetal biometry, anomaly scans, growth assessment, and high-risk pregnancy imaging with detailed reporting." },
    { icon: "Microscope", title: "Diagnostic X-Ray", description: "Digital X-ray interpretation for chest, skeletal, and abdominal radiographs with accurate reporting." },
  ],
  conditions: [
    "MRI Brain & Spine", "3T Neuroimaging", "Breast Imaging", "Obstetric Ultrasound",
    "Abdominal Imaging", "Musculoskeletal MRI", "CT Head & Body", "Thyroid Ultrasound",
    "Doppler Studies", "Fetal Anomaly Scan", "HSG & Mammography", "USG Guided Procedures",
    "Chest X-Ray", "Skeletal Survey", "Contrast Studies", "Interventional Radiology",
  ],
  education: [
    { degree: "MD (Radiology)", detail: "Doctor of Medicine in Radiology", icon: "GraduationCap" },
    { degree: "MBBS", detail: "Bachelor of Medicine & Bachelor of Surgery", icon: "Stethoscope" },
  ],
  highlights: [
    { icon: "Microscope", title: "3 Tesla MRI Expertise", description: "High-field 3T MRI reporting for superior image quality and diagnostic confidence." },
    { icon: "HeartPulse", title: "Women's Imaging Focus", description: "Specialized care in breast imaging, obstetric scans, and women's health diagnostics." },
    { icon: "CheckCircle2", title: "Accurate Reporting", description: "Detailed, clinically-correlated reports that help referring doctors make better decisions." },
    { icon: "Clock", title: "Quick Turnaround", description: "Fast report delivery for OPD and emergency studies, without compromising accuracy." },
  ],
  facilities: [
    { image: "/gallery-ot.jpg", title: "3 Tesla MRI Suite", description: "State-of-the-art 3 Tesla MRI scanner delivering high-resolution images for neuro, musculoskeletal, and abdominal imaging." },
    { image: "/gallery-icu.jpg", title: "CT Scan Facility", description: "Multi-slice CT scanner for rapid, high-quality imaging of head, chest, abdomen, and vascular studies." },
    { image: "/gallery-consult.jpg", title: "Ultrasound Room", description: "Advanced ultrasound machines for abdominal, obstetric, Doppler, and women's imaging with patient comfort." },
    { image: "/gallery-hospital.jpg", title: "Care Diagnostics", description: "A fully equipped diagnostic imaging center serving Deoghar and surrounding regions of Jharkhand." },
  ],
  stats: [
    { label: "Years of Radiology Experience", value: 8, suffix: "+" },
    { label: "MRI Studies Reported", value: 5000, suffix: "+" },
    { label: "Women's Imaging Studies", value: 3000, suffix: "+" },
    { label: "Accurate Diagnoses", value: 20000, suffix: "+" },
  ],
  social: { facebook: "", instagram: "", youtube: "", linkedin: "", twitter: "" },
  nav: [
    { label: "Home", href: "#home" },
    { label: "About", href: "#about" },
    { label: "Expertise", href: "#expertise" },
    { label: "Services", href: "#services" },
    { label: "Facilities", href: "#facilities" },
    { label: "Credentials", href: "#credentials" },
    { label: "Location", href: "#location" },
    { label: "Contact", href: "#contact" },
  ],
  theme: { primary: "#a34355", primaryDark: "#853a49", accent: "#c9a24b" },
};

export type SiteConfig = typeof siteConfig;
